@user_id = 7e7f96f9-b2bd-4f70-b6a1-30ffc328f242

###

POST http://127.0.0.1:8000/user
Content-Type: application/json

{
  "name": "Jon",
  "password": "Doe",
  "money": 0,
  "admin": false
}

###

GET http://127.0.0.1:8000/user/{{user_id}}

###

PUT http://127.0.0.1:8000/user/{{user_id}}
Content-Type: application/json

{
  "name": "Jon",
  "password": "Doe",
  "money": 1000,
  "admin": false
}

###

DELETE http://127.0.0.1:8000/user/{{user_id}}

###

GET http://127.0.0.1:8000/users

###

POST http://127.0.0.1:8000/login/{{user_id}}

