@id = 47a42455-d363-4ffb-9c18-ab05e20e84cc

###

POST http://localhost:8080/user
Content-Type: application/json

{
  "name": "John Doe",
  "password": "12345"
}

###

GET http://localhost:8080/user/{{id}}

###

PUT http://localhost:8080/user/{{id}}
Content-Type: application/json

{
  "name": "Jane Doe",
  "password": "54321"
}

###

DELETE http://localhost:8080/user/{{id}}

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "name": "John Doe",
  "password": "54321"
}